services:
  db:
    image: mysql:8.1
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpressapp
      MYSQL_PASSWORD: secureit!
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
    volumes:
      - db:/var/lib/mysql
    restart: always
  
  wordpress:
    image: wordpress:6.3-apache
    ports:
      - 8080:80
    depends_on:
      - db
    volumes:
    - wordpress:/var/www/html
    restart: always

volumes:
  wordpress:
  db: